CREATE DATABASE ICARUS; USE ICARUS;

CREATE TABLE USU_USUARIO ( USU_ID BIGINT NOT NULL IDENTITY, USU_NOME VARCHAR(50) NOT NULL, USU_SOBRENOME VARCHAR(200) NOT NULL, USU_EMAIL VARCHAR(150) NOT NULL UNIQUE, USU_SENHA VARCHAR(100) NOT NULL, PRIMARY KEY(USU_ID, USU_EMAIL) ); 